### ISSUE TITLE
Any way to modify the message before the song name?

### ISSUE THREAD

**Issue by syntaxxl** [o0F-0oF/VRChat-Spotify-Chatbox#1]

**Comment by o0F-0oF** [comment]
if you modify this line you can modify it
https://github.com/o0F-0oF/VRChat-Spotify-Chatbox/blob/91179d812a87b8622e17815b42ed34851226e9b1/vsc.py#L67
or on this line change the true too false to manually send it 
https://github.com/o0F-0oF/VRChat-Spotify-Chatbox/blob/91179d812a87b8622e17815b42ed34851226e9b1/vsc.py#L11
